apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lhp98p0ae-python 
  janus-idp.io/tekton: lhp98p0ae-python
  backstage.io/kubernetes-id: lhp98p0ae-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lhp98p0ae-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml