apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lhp98p0ae-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lhp98p0ae-python 
  name: lhp98p0ae-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lhp98p0ae-python 
